<?php

$liste_champs_Jugement = [
  "", "id_tribunal", "num_jugement", "num_dossier", "annee_dossier", "jd_etablissement_jugement_h", "md_etablissement_jugement_h", "ad_etablissement_jugement_h", "jd_etablissement_jugement_g", "md_etablissement_jugement_g", "ad_etablissement_jugement_g", "j_prononciation_jugement_g", "md_prononciation_jugement_g", "ad_prononciation_jugement_g", "j_prononciation_jugement_h", "md_prononciation_jugement_h", "ad_prononciation_jugement_h", "j_reception_jugement_g", "md_reception_jugement_g", "ad_reception_jugement_g", "j_reception_jugement_h", "md_reception_jugement_h", "ad_reception_jugement_h"
];

$liste_champs_deces = [
  "", "jd_deces_h", "md_deces_h", "ad_deces_h", "jd_deces_g", "md_deces_g", "ad_deces_g", "heure_deces", "minute_deces", "lieu_deces", "lieuresidence", "lieu_residence_pere_ar", "lieu_residence_mere_ar", "id_profession", "statutfamilialle"
];

$liste_champs_actes = [
  ["cposition" => 1, "cname" => "id_acte"],
  ["cposition" => 2, "cname" => "id_type_acte"],
  ["cposition" => 3, "cname" => "id_tome_registre"],
  ["cposition" => 4, "cname" => "num_acte"],
  ["cposition" => 5, "cname" => "annee_acte"],
  ["cposition" => 6, "cname" => "jd_naissance_h"],
  ["cposition" => 7, "cname" => "md_naissance_h"],
  ["cposition" => 8, "cname" => "ad_naissance_h"],
  ["cposition" => 9, "cname" => "jd_naissance_g"],
  ["cposition" => 10, "cname" => "md_naissance_g"],
  ["cposition" => 11, "cname" => "ad_naissance_g"],
  ["cposition" => 12, "cname" => "heure_naissance"],
  ["cposition" => 13, "cname" => "minute_naissance"],
  ["cposition" => 14, "cname" => "lieu_naissance"],
  ["cposition" => 15, "cname" => "jumeaux"],
  ["cposition" => 16, "cname" => "prenom_ar"],
  ["cposition" => 17, "cname" => "prenom_fr"],
  ["cposition" => 18, "cname" => "nom_ar"],
  ["cposition" => 19, "cname" => "nom_fr"],
  ["cposition" => 20, "cname" => "nom_marge_ar"],
  ["cposition" => 21, "cname" => "prenom_marge_fr"],
  ["cposition" => 22, "cname" => "nom_marge_fr"],
  ["cposition" => 23, "cname" => "prenom_marge_ar"],
  ["cposition" => 24, "cname" => "sexe"],
  ["cposition" => 25, "cname" => "id_nationlite"],
  ["cposition" => 26, "cname" => "decede_pere"],
  ["cposition" => 27, "cname" => "prenom_pere_ar"],
  ["cposition" => 28, "cname" => "prenom_pere_fr"],
  ["cposition" => 29, "cname" => "ascendant_pere_ar"],
  ["cposition" => 30, "cname" => "ascendant_pere_fr"],
  ["cposition" => 31, "cname" => "id_nationalite_pere"],
  ["cposition" => 32, "cname" => "id_profession_pere"],
  ["cposition" => 33, "cname" => "jd_naissance_pere_h"],
  ["cposition" => 34, "cname" => "md_naissance_pere_h"],
  ["cposition" => 35, "cname" => "ad_naissance_pere_h"],
  ["cposition" => 36, "cname" => "jd_naissance_pere_g"],
  ["cposition" => 37, "cname" => "md_naissance_pere_g"],
  ["cposition" => 38, "cname" => "ad_naissance_pere_g"],
  ["cposition" => 39, "cname" => "lieu_naissance_pere"],
  ["cposition" => 40, "cname" => "decede_mere"],
  ["cposition" => 41, "cname" => "prenom_mere_ar"],
  ["cposition" => 42, "cname" => "prenom_mere_fr"],
  ["cposition" => 43, "cname" => "ascendant_mere_ar"],
  ["cposition" => 44, "cname" => "ascendant_mere_fr"],
  ["cposition" => 45, "cname" => "id_nationalite_mere"],
  ["cposition" => 46, "cname" => "id_profession_mere"],
  ["cposition" => 47, "cname" => "jd_naissance_mere_h"],
  ["cposition" => 48, "cname" => "md_naissance_mere_h"],
  ["cposition" => 49, "cname" => "ad_naissance_mere_h"],
  ["cposition" => 50, "cname" => "jd_naissance_mere_g"],
  ["cposition" => 51, "cname" => "md_naissance_mere_g"],
  ["cposition" => 52, "cname" => "ad_naissance_mere_g"],
  ["cposition" => 53, "cname" => "lieu_naissance_mere"],
  ["cposition" => 54, "cname" => "adresse_residence_parents"],
  ["cposition" => 55, "cname" => "jd_etabli_acte_h"],
  ["cposition" => 56, "cname" => "ad_etabli_acte_h"],
  ["cposition" => 57, "cname" => "md_etabli_acte_h"],
  ["cposition" => 58, "cname" => "jd_etabli_acte_g"],
  ["cposition" => 59, "cname" => "ad_etabli_acte_g"],
  ["cposition" => 60, "cname" => "md_etabli_acte_g"],
  ["cposition" => 61, "cname" => "id_officier"],
  ["cposition" => 62, "cname" => "annee_acte_g"],
  ["cposition" => 63, "cname" => "lieu_naissance_fr"],
  ["cposition" => 64, "cname" => "lieu_naissance_pere_fr"],
  ["cposition" => 65, "cname" => "lieu_naissance_mere_fr"],
  ["cposition" => 66, "cname" => "adresse_residence_parents_fr"],
  ["cposition" => 67, "cname" => "sign_officier"],
  ["cposition" => 68, "cname" => "sceau_officier"],
  ["cposition" => 69, "cname" => "status_acte"],
  ["cposition" => 70, "cname" => "heure_etabli_acte"],
  ["cposition" => 71, "cname" => "minute_etabli_acte"],
  ["cposition" => 72, "cname" => "utilisateur_creation"],
  ["cposition" => 73, "cname" => "date_creation"],
  ["cposition" => 74, "cname" => "utilisateur_modification"],
  ["cposition" => 75, "cname" => "date_modification"],
  ["cposition" => 76, "cname" => "id_bureau"],
  ["cposition" => 77, "cname" => "id_commune"],
  ["cposition" => 78, "cname" => "status_acteechantillon"],
  ["cposition" => 79, "cname" => "langue_acte"],
  ["cposition" => 80, "cname" => "id_ville_naissance"],
  ["cposition" => 81, "cname" => "id_ville_naissance_mere"],
  ["cposition" => 82, "cname" => "id_ville_naissance_pere"],
  ["cposition" => 83, "cname" => "id_ville_residence_parents"],
  ["cposition" => 84, "cname" => "date_statut_oec"],
  ["cposition" => 85, "cname" => "imagepath"],
  ["cposition" => 86, "cname" => "image1"],
  ["cposition" => 87, "cname" => "image2"],
  ["cposition" => 88, "cname" => "image3"],
  ["cposition" => 89, "cname" => "image4"],
  ["cposition" => 90, "cname" => "lisible1"],
  ["cposition" => 91, "cname" => "lisible2"],
  ["cposition" => 92, "cname" => "lisible3"],
  ["cposition" => 93, "cname" => "lisible4"],
  ["cposition" => 94, "cname" => "remarque"]
];

// Tableau champs à griser 
$champs_gris = ['', 'id_lot', 'id_acte', 'id_type_acte', 'id_tome_registre', 'utilisateur_creation', 'date_creation', 'utilisateur_modification', 'date_modification', 'id_bureau', 'id_commune', 'status_acteechantillon', 'id_ville_naissance', 'id_ville_naissance_pere', 'id_ville_naissance_mere', 'id_ville_residence_parents', 'date_statut_oec', 'image1', 'image2', 'image3', 'image4', 'lisible1', 'lisible2', 'lisible3', 'lisible4'];
